### PR TITLE
Add a note about using the model trait for this to work and support array values

### PR DESCRIPTION
**Pull request by tonypartridge**

### CODE REVIEW

**Comment by tonypartridge** [comment]
Now updated to support array stored items.

**Comment by ziming** [comment]
Looking forward to this!

**Comment by pxlrbt** [comment]
Thanks Tony. Merged.

**Comment by pxlrbt** [comment]
@ziming I don't have a Filament v3 app yet that uses Activity Log, so this probably needs to wait a bit.

**Pull request merged**
